// Code generated by protoc-gen-go. DO NOT EDIT.
// source: arbitragebooksmessage.proto

package orderbook

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ArbitrageBooksMessage struct {
	Book1                *OrderBook `protobuf:"bytes,1,opt,name=Book1,proto3" json:"Book1,omitempty"`
	Book2                *OrderBook `protobuf:"bytes,2,opt,name=Book2,proto3" json:"Book2,omitempty"`
	Crossbook            *OrderBook `protobuf:"bytes,3,opt,name=Crossbook,proto3" json:"Crossbook,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ArbitrageBooksMessage) Reset()         { *m = ArbitrageBooksMessage{} }
func (m *ArbitrageBooksMessage) String() string { return proto.CompactTextString(m) }
func (*ArbitrageBooksMessage) ProtoMessage()    {}
func (*ArbitrageBooksMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_840d189b28177993, []int{0}
}

func (m *ArbitrageBooksMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArbitrageBooksMessage.Unmarshal(m, b)
}
func (m *ArbitrageBooksMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArbitrageBooksMessage.Marshal(b, m, deterministic)
}
func (m *ArbitrageBooksMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArbitrageBooksMessage.Merge(m, src)
}
func (m *ArbitrageBooksMessage) XXX_Size() int {
	return xxx_messageInfo_ArbitrageBooksMessage.Size(m)
}
func (m *ArbitrageBooksMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ArbitrageBooksMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ArbitrageBooksMessage proto.InternalMessageInfo

func (m *ArbitrageBooksMessage) GetBook1() *OrderBook {
	if m != nil {
		return m.Book1
	}
	return nil
}

func (m *ArbitrageBooksMessage) GetBook2() *OrderBook {
	if m != nil {
		return m.Book2
	}
	return nil
}

func (m *ArbitrageBooksMessage) GetCrossbook() *OrderBook {
	if m != nil {
		return m.Crossbook
	}
	return nil
}

func init() {
	proto.RegisterType((*ArbitrageBooksMessage)(nil), "orderbook.ArbitrageBooksMessage")
}

func init() { proto.RegisterFile("arbitragebooksmessage.proto", fileDescriptor_840d189b28177993) }

var fileDescriptor_840d189b28177993 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x2c, 0x4a, 0xca,
	0x2c, 0x29, 0x4a, 0x4c, 0x4f, 0x4d, 0xca, 0xcf, 0xcf, 0x2e, 0xce, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc, 0x2f, 0x4a, 0x49, 0x2d, 0x02, 0x49,
	0x48, 0xf1, 0xc3, 0x99, 0x10, 0x39, 0xa5, 0xc5, 0x8c, 0x5c, 0xa2, 0x8e, 0x30, 0xbd, 0x4e, 0x20,
	0xbd, 0xbe, 0x10, 0xbd, 0x42, 0x5a, 0x5c, 0xac, 0x20, 0xbe, 0xa1, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0xb7, 0x91, 0x88, 0x1e, 0x42, 0xab, 0x3f, 0x88, 0x05, 0x92, 0x0c, 0x82, 0x28, 0x81, 0xa9, 0x35,
	0x92, 0x60, 0x22, 0xa4, 0xd6, 0x48, 0xc8, 0x88, 0x8b, 0xd3, 0xb9, 0x28, 0xbf, 0xb8, 0x18, 0x24,
	0x2b, 0xc1, 0x8c, 0x47, 0x3d, 0x42, 0x59, 0x12, 0x1b, 0xd8, 0xb1, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xee, 0xb7, 0x06, 0x2f, 0xe7, 0x00, 0x00, 0x00,
}
