// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderbook/orderbook.proto

package orderbook

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Exchange int32

const (
	Exchange_UnknownExchange Exchange = 0
	Exchange_Idex            Exchange = 1
	Exchange_EtherDelta      Exchange = 2
	Exchange_ForkDelta       Exchange = 3
	Exchange_Binance         Exchange = 4
	Exchange_HitBTC          Exchange = 5
	Exchange_Mercatox        Exchange = 6
	Exchange_Huobi           Exchange = 7
	Exchange_Hadax           Exchange = 8
	Exchange_Bitfinex        Exchange = 9
	Exchange_Ethfinex        Exchange = 10
	Exchange_Coinex          Exchange = 11
	Exchange_Kucoin          Exchange = 12
	Exchange_Okex            Exchange = 13
	Exchange_Bittrex         Exchange = 14
	Exchange_Bibox           Exchange = 15
	Exchange_Bilaxy          Exchange = 16
	Exchange_Tidex           Exchange = 17
	Exchange_Ddex            Exchange = 18
	Exchange_Coinegg         Exchange = 19
	Exchange_Lbank           Exchange = 20
	Exchange_BigOne          Exchange = 21
	Exchange_Coinbene        Exchange = 22
	Exchange_Liqui           Exchange = 23
	Exchange_Cobinhood       Exchange = 24
	Exchange_Gate            Exchange = 25
	Exchange_Bcex            Exchange = 26
	Exchange_Kraken          Exchange = 27
	Exchange_Liquid          Exchange = 28
	Exchange_Gdax            Exchange = 29
	Exchange_Poloniex        Exchange = 30
)

var Exchange_name = map[int32]string{
	0:  "UnknownExchange",
	1:  "Idex",
	2:  "EtherDelta",
	3:  "ForkDelta",
	4:  "Binance",
	5:  "HitBTC",
	6:  "Mercatox",
	7:  "Huobi",
	8:  "Hadax",
	9:  "Bitfinex",
	10: "Ethfinex",
	11: "Coinex",
	12: "Kucoin",
	13: "Okex",
	14: "Bittrex",
	15: "Bibox",
	16: "Bilaxy",
	17: "Tidex",
	18: "Ddex",
	19: "Coinegg",
	20: "Lbank",
	21: "BigOne",
	22: "Coinbene",
	23: "Liqui",
	24: "Cobinhood",
	25: "Gate",
	26: "Bcex",
	27: "Kraken",
	28: "Liquid",
	29: "Gdax",
	30: "Poloniex",
}

var Exchange_value = map[string]int32{
	"UnknownExchange": 0,
	"Idex":            1,
	"EtherDelta":      2,
	"ForkDelta":       3,
	"Binance":         4,
	"HitBTC":          5,
	"Mercatox":        6,
	"Huobi":           7,
	"Hadax":           8,
	"Bitfinex":        9,
	"Ethfinex":        10,
	"Coinex":          11,
	"Kucoin":          12,
	"Okex":            13,
	"Bittrex":         14,
	"Bibox":           15,
	"Bilaxy":          16,
	"Tidex":           17,
	"Ddex":            18,
	"Coinegg":         19,
	"Lbank":           20,
	"BigOne":          21,
	"Coinbene":        22,
	"Liqui":           23,
	"Cobinhood":       24,
	"Gate":            25,
	"Bcex":            26,
	"Kraken":          27,
	"Liquid":          28,
	"Gdax":            29,
	"Poloniex":        30,
}

func (x Exchange) String() string {
	return proto.EnumName(Exchange_name, int32(x))
}

func (Exchange) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_233e91af0692daf8, []int{0}
}

type Market int32

const (
	Market_UnknownMarket Market = 0
	Market_BTC           Market = 1
	Market_ETH           Market = 2
	Market_USDT          Market = 3
	Market_TUSD          Market = 4
	Market_USD           Market = 5
	Market_USDC          Market = 6
	Market_GUSD          Market = 7
	Market_BNB           Market = 8
	Market_BIX           Market = 9
	Market_DAI           Market = 10
	Market_BCH           Market = 11
	Market_CET           Market = 12
	Market_QTUM          Market = 13
	Market_NEO           Market = 14
	Market_KCS           Market = 15
	Market_EOS           Market = 16
	Market_EUR           Market = 17
	Market_GBP           Market = 18
	Market_JPY           Market = 19
	Market_COB           Market = 20
)

var Market_name = map[int32]string{
	0:  "UnknownMarket",
	1:  "BTC",
	2:  "ETH",
	3:  "USDT",
	4:  "TUSD",
	5:  "USD",
	6:  "USDC",
	7:  "GUSD",
	8:  "BNB",
	9:  "BIX",
	10: "DAI",
	11: "BCH",
	12: "CET",
	13: "QTUM",
	14: "NEO",
	15: "KCS",
	16: "EOS",
	17: "EUR",
	18: "GBP",
	19: "JPY",
	20: "COB",
}

var Market_value = map[string]int32{
	"UnknownMarket": 0,
	"BTC":           1,
	"ETH":           2,
	"USDT":          3,
	"TUSD":          4,
	"USD":           5,
	"USDC":          6,
	"GUSD":          7,
	"BNB":           8,
	"BIX":           9,
	"DAI":           10,
	"BCH":           11,
	"CET":           12,
	"QTUM":          13,
	"NEO":           14,
	"KCS":           15,
	"EOS":           16,
	"EUR":           17,
	"GBP":           18,
	"JPY":           19,
	"COB":           20,
}

func (x Market) String() string {
	return proto.EnumName(Market_name, int32(x))
}

func (Market) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_233e91af0692daf8, []int{1}
}

type OrderBook struct {
	LastUpdateId         int64    `protobuf:"varint,1,opt,name=LastUpdateId,proto3" json:"LastUpdateId,omitempty"`
	Exchange             Exchange `protobuf:"varint,2,opt,name=Exchange,proto3,enum=orderbook.Exchange" json:"Exchange,omitempty"`
	Market               Market   `protobuf:"varint,3,opt,name=Market,proto3,enum=orderbook.Market" json:"Market,omitempty"`
	Ticker               string   `protobuf:"bytes,4,opt,name=Ticker,proto3" json:"Ticker,omitempty"`
	Asks                 []*Order `protobuf:"bytes,5,rep,name=Asks,proto3" json:"Asks,omitempty"`
	Bids                 []*Order `protobuf:"bytes,6,rep,name=Bids,proto3" json:"Bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBook) Reset()         { *m = OrderBook{} }
func (m *OrderBook) String() string { return proto.CompactTextString(m) }
func (*OrderBook) ProtoMessage()    {}
func (*OrderBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_233e91af0692daf8, []int{0}
}

func (m *OrderBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBook.Unmarshal(m, b)
}
func (m *OrderBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBook.Marshal(b, m, deterministic)
}
func (m *OrderBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBook.Merge(m, src)
}
func (m *OrderBook) XXX_Size() int {
	return xxx_messageInfo_OrderBook.Size(m)
}
func (m *OrderBook) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBook.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBook proto.InternalMessageInfo

func (m *OrderBook) GetLastUpdateId() int64 {
	if m != nil {
		return m.LastUpdateId
	}
	return 0
}

func (m *OrderBook) GetExchange() Exchange {
	if m != nil {
		return m.Exchange
	}
	return Exchange_UnknownExchange
}

func (m *OrderBook) GetMarket() Market {
	if m != nil {
		return m.Market
	}
	return Market_UnknownMarket
}

func (m *OrderBook) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *OrderBook) GetAsks() []*Order {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *OrderBook) GetBids() []*Order {
	if m != nil {
		return m.Bids
	}
	return nil
}

type OrderBookDiff struct {
	LastUpdateId         int64    `protobuf:"varint,1,opt,name=LastUpdateId,proto3" json:"LastUpdateId,omitempty"`
	Exchange             Exchange `protobuf:"varint,2,opt,name=Exchange,proto3,enum=orderbook.Exchange" json:"Exchange,omitempty"`
	Market               Market   `protobuf:"varint,3,opt,name=Market,proto3,enum=orderbook.Market" json:"Market,omitempty"`
	Ticker               string   `protobuf:"bytes,4,opt,name=Ticker,proto3" json:"Ticker,omitempty"`
	Asks                 []*Order `protobuf:"bytes,5,rep,name=Asks,proto3" json:"Asks,omitempty"`
	Bids                 []*Order `protobuf:"bytes,6,rep,name=Bids,proto3" json:"Bids,omitempty"`
	FirstUpdateId        int64    `protobuf:"varint,7,opt,name=FirstUpdateId,proto3" json:"FirstUpdateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBookDiff) Reset()         { *m = OrderBookDiff{} }
func (m *OrderBookDiff) String() string { return proto.CompactTextString(m) }
func (*OrderBookDiff) ProtoMessage()    {}
func (*OrderBookDiff) Descriptor() ([]byte, []int) {
	return fileDescriptor_233e91af0692daf8, []int{1}
}

func (m *OrderBookDiff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBookDiff.Unmarshal(m, b)
}
func (m *OrderBookDiff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBookDiff.Marshal(b, m, deterministic)
}
func (m *OrderBookDiff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookDiff.Merge(m, src)
}
func (m *OrderBookDiff) XXX_Size() int {
	return xxx_messageInfo_OrderBookDiff.Size(m)
}
func (m *OrderBookDiff) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookDiff.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookDiff proto.InternalMessageInfo

func (m *OrderBookDiff) GetLastUpdateId() int64 {
	if m != nil {
		return m.LastUpdateId
	}
	return 0
}

func (m *OrderBookDiff) GetExchange() Exchange {
	if m != nil {
		return m.Exchange
	}
	return Exchange_UnknownExchange
}

func (m *OrderBookDiff) GetMarket() Market {
	if m != nil {
		return m.Market
	}
	return Market_UnknownMarket
}

func (m *OrderBookDiff) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *OrderBookDiff) GetAsks() []*Order {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *OrderBookDiff) GetBids() []*Order {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *OrderBookDiff) GetFirstUpdateId() int64 {
	if m != nil {
		return m.FirstUpdateId
	}
	return 0
}

type Order struct {
	Price                float32  `protobuf:"fixed32,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity             float32  `protobuf:"fixed32,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_233e91af0692daf8, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterEnum("orderbook.Exchange", Exchange_name, Exchange_value)
	proto.RegisterEnum("orderbook.Market", Market_name, Market_value)
	proto.RegisterType((*OrderBook)(nil), "orderbook.OrderBook")
	proto.RegisterType((*OrderBookDiff)(nil), "orderbook.OrderBookDiff")
	proto.RegisterType((*Order)(nil), "orderbook.Order")
}

func init() { proto.RegisterFile("orderbook/orderbook.proto", fileDescriptor_233e91af0692daf8) }

var fileDescriptor_233e91af0692daf8 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x94, 0x4b, 0x52, 0xdb, 0x4c,
	0x10, 0xc7, 0x91, 0xdf, 0x1a, 0x63, 0xd3, 0x1e, 0xf3, 0xf1, 0x09, 0xf2, 0x28, 0x97, 0x8b, 0x85,
	0xc3, 0x02, 0xaa, 0xc8, 0x2a, 0x4b, 0x24, 0x1b, 0xec, 0xf0, 0xb0, 0x91, 0xe5, 0xaa, 0x64, 0x39,
	0x92, 0x06, 0x7b, 0x4a, 0xd4, 0x0c, 0x91, 0xc7, 0x15, 0x71, 0x87, 0x5c, 0x20, 0xf7, 0xca, 0x3d,
	0x72, 0x85, 0x54, 0x8f, 0x8c, 0x81, 0x45, 0x4e, 0x90, 0xdd, 0xaf, 0xbb, 0xff, 0xfd, 0x9f, 0xee,
	0xb6, 0x4b, 0x64, 0x5f, 0xa5, 0x31, 0x4f, 0x43, 0xa5, 0x92, 0x93, 0x0d, 0x1d, 0x3f, 0xa4, 0x4a,
	0x2b, 0x6a, 0x6f, 0x12, 0xdd, 0xdf, 0x16, 0xb1, 0xc7, 0x18, 0xb9, 0x4a, 0x25, 0xb4, 0x4b, 0xb6,
	0xaf, 0xd8, 0x52, 0xcf, 0x1e, 0x62, 0xa6, 0xf9, 0x28, 0x76, 0xac, 0x8e, 0xd5, 0x2b, 0xfa, 0xaf,
	0x72, 0xf4, 0x84, 0xd4, 0x06, 0x59, 0xb4, 0x60, 0x72, 0xce, 0x9d, 0x42, 0xc7, 0xea, 0x35, 0x4f,
	0xdb, 0xc7, 0xcf, 0x0f, 0x3c, 0x95, 0xfc, 0x8d, 0x88, 0x7e, 0x20, 0x95, 0x6b, 0x96, 0x26, 0x5c,
	0x3b, 0x45, 0x23, 0x6f, 0xbd, 0x90, 0xe7, 0x05, 0x7f, 0x2d, 0xa0, 0x7b, 0xa4, 0x12, 0x88, 0x28,
	0xe1, 0xa9, 0x53, 0xea, 0x58, 0x3d, 0xdb, 0x5f, 0x47, 0xf4, 0x90, 0x94, 0xce, 0x96, 0xc9, 0xd2,
	0x29, 0x77, 0x8a, 0xbd, 0xfa, 0x29, 0xbc, 0x30, 0x30, 0xb3, 0xfb, 0xa6, 0x8a, 0x2a, 0x57, 0xc4,
	0x4b, 0xa7, 0xf2, 0x37, 0x15, 0x56, 0xbb, 0x3f, 0x0b, 0xa4, 0xb1, 0xd9, 0xb8, 0x2f, 0xee, 0xee,
	0xfe, 0x85, 0xad, 0xe9, 0x21, 0x69, 0x9c, 0x8b, 0xf4, 0xc5, 0x92, 0x55, 0xb3, 0xe4, 0xeb, 0x64,
	0xf7, 0x13, 0x29, 0x9b, 0x26, 0xba, 0x4b, 0xca, 0x93, 0x54, 0x44, 0xdc, 0xdc, 0xa2, 0xe0, 0xe7,
	0x01, 0x3d, 0x20, 0xb5, 0xdb, 0x15, 0x93, 0x5a, 0xe8, 0x47, 0x73, 0x84, 0x82, 0xbf, 0x89, 0x8f,
	0x7e, 0x14, 0x9f, 0x2f, 0x44, 0xdb, 0x64, 0x67, 0x26, 0x13, 0xa9, 0xbe, 0xcb, 0xa7, 0x14, 0x6c,
	0xd1, 0x1a, 0x29, 0x8d, 0x62, 0x9e, 0x81, 0x45, 0x9b, 0x84, 0x0c, 0xf4, 0x82, 0xa7, 0x7d, 0x7e,
	0xaf, 0x19, 0x14, 0x68, 0x83, 0xd8, 0xe7, 0x2a, 0x4d, 0xf2, 0xb0, 0x48, 0xeb, 0xa4, 0xea, 0x0a,
	0xc9, 0x64, 0xc4, 0xa1, 0x44, 0x09, 0xa9, 0x0c, 0x85, 0x76, 0x03, 0x0f, 0xca, 0x74, 0x9b, 0xd4,
	0xae, 0x79, 0x1a, 0x31, 0xad, 0x32, 0xa8, 0x50, 0x9b, 0x94, 0x87, 0x2b, 0x15, 0x0a, 0xa8, 0x1a,
	0x64, 0x31, 0xcb, 0xa0, 0x86, 0x1a, 0x57, 0xe8, 0x3b, 0x21, 0x79, 0x06, 0x36, 0x46, 0x03, 0xbd,
	0xc8, 0x23, 0x82, 0x5e, 0x9e, 0x32, 0x5c, 0x47, 0xbe, 0x5c, 0x45, 0x4a, 0x48, 0xd8, 0xc6, 0xc9,
	0xc6, 0x09, 0xcf, 0xa0, 0x91, 0x3f, 0xad, 0x75, 0xca, 0x33, 0x68, 0xa2, 0xab, 0x2b, 0x42, 0x95,
	0xc1, 0x0e, 0xaa, 0x5d, 0x71, 0xcf, 0xb2, 0x47, 0x00, 0x4c, 0x07, 0x02, 0x17, 0x69, 0x61, 0x63,
	0x1f, 0x89, 0x62, 0xa3, 0xb1, 0x9e, 0xcf, 0xa1, 0x8d, 0x8a, 0xab, 0x90, 0xc9, 0x04, 0x76, 0xf3,
	0xc6, 0xf9, 0x58, 0x72, 0xf8, 0x0f, 0x87, 0x41, 0x4d, 0xc8, 0x25, 0x87, 0x3d, 0x23, 0x12, 0xdf,
	0x56, 0x02, 0xfe, 0xc7, 0xfd, 0x3d, 0x15, 0x0a, 0xb9, 0x50, 0x2a, 0x06, 0x07, 0x5d, 0x2f, 0x98,
	0xe6, 0xb0, 0x8f, 0xe4, 0x46, 0x3c, 0x83, 0x03, 0x33, 0x6e, 0xca, 0x12, 0x2e, 0xe1, 0x0d, 0xb2,
	0xe9, 0x8c, 0xe1, 0xad, 0xd1, 0xe2, 0xe2, 0xef, 0xd0, 0x7d, 0xa2, 0xee, 0x95, 0x14, 0x3c, 0x83,
	0xf7, 0x47, 0xbf, 0xac, 0xa7, 0xff, 0x1f, 0x6d, 0x91, 0xc6, 0xfa, 0xc7, 0xc8, 0x13, 0xb0, 0x45,
	0xab, 0xa4, 0x88, 0x17, 0xb5, 0x10, 0x06, 0xc1, 0x10, 0x0a, 0xe8, 0x33, 0x9b, 0xf6, 0x03, 0x28,
	0x22, 0x05, 0xb3, 0x69, 0x1f, 0x4a, 0x58, 0x44, 0x28, 0xaf, 0x8b, 0x1e, 0x54, 0xcc, 0x73, 0x98,
	0xab, 0x1a, 0x8b, 0x1b, 0x17, 0x6a, 0x06, 0x46, 0x5f, 0xc0, 0x46, 0xe8, 0x9f, 0x8d, 0x80, 0x98,
	0x8c, 0x37, 0x84, 0x3a, 0x82, 0x37, 0x08, 0xf2, 0x03, 0xdf, 0x06, 0xb3, 0x6b, 0x68, 0x60, 0xea,
	0x66, 0x30, 0x86, 0x26, 0xc2, 0xa5, 0x37, 0x85, 0x1d, 0x33, 0xc2, 0x78, 0x0a, 0x60, 0x60, 0xe6,
	0x43, 0x0b, 0xe1, 0xc2, 0x9d, 0x00, 0x45, 0xf8, 0x3c, 0xf9, 0x0a, 0x6d, 0x63, 0x34, 0x76, 0x61,
	0x37, 0xac, 0x98, 0x0f, 0xd8, 0xc7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x0e, 0x22, 0xf2,
	0xdd, 0x04, 0x00, 0x00,
}
